import { useMemo, useState } from "react";
import {
  AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, Info, Save, Trash2, Upload,
} from "lucide-react";
import PageHeader from "@/components/layout/PageHeader";
import Button from "@/components/ui/Button";
import Select from "@/components/ui/Select";
import Input from "@/components/ui/Input";
import Checkbox from "@/components/ui/Checkbox";
import Badge from "@/components/ui/Badge";
import Tabs from "@/components/ui/Tabs";
import FileUpload from "@/components/ui/FileUpload";
import EmptyState from "@/components/ui/EmptyState";
import { toast } from "@/components/ui/Toast";
import {
  useGetImportCatalogueQuery,
  useInspectImportFileMutation,
  useValidateImportMutation,
  useCommitImportMutation,
  useGetImportMappingsQuery,
  useSaveImportMappingMutation,
  useDeleteImportMappingMutation,
} from "./bulkImportApiSlice";

/**
 * Bring an existing estate in from a spreadsheet.
 *
 * Three imports in a fixed order, because each depends on the one before:
 * properties, then units across every property, then tenants into those units.
 * The order is shown rather than enforced — someone adding units to blocks that
 * are already on the system should not have to run a properties import first.
 *
 * Four steps: choose a file, say which column means what, look at what will
 * happen, then commit. Nothing is written until the last one, and the preview
 * is generated by the same validation the commit re-runs server-side.
 */

const STEPS = ["Upload", "Map columns", "Preview", "Done"];

function StepBar({ step }) {
  return (
    <ol className="mb-6 flex flex-wrap items-center gap-2 text-sm">
      {STEPS.map((label, index) => {
        const state = index < step ? "done" : index === step ? "current" : "todo";
        return (
          <li key={label} className="flex items-center gap-2">
            <span
              className={
                state === "current"
                  ? "flex h-6 w-6 items-center justify-center rounded-full bg-secondary text-xs font-semibold text-white"
                  : state === "done"
                  ? "flex h-6 w-6 items-center justify-center rounded-full bg-emerald-500/80 text-xs text-white"
                  : "flex h-6 w-6 items-center justify-center rounded-full bg-white/10 text-xs text-white/40"
              }
            >
              {state === "done" ? "✓" : index + 1}
            </span>
            <span className={state === "todo" ? "text-white/35" : "text-white/80"}>{label}</span>
            {index < STEPS.length - 1 && <span className="px-1 text-white/20">→</span>}
          </li>
        );
      })}
    </ol>
  );
}

export default function BulkImportPage() {
  const { data: catalogue } = useGetImportCatalogueQuery();
  const entities = catalogue?.entities ?? [];

  const [entity, setEntity] = useState("properties");
  const [step, setStep] = useState(0);
  const [file, setFile] = useState(null);
  const [parsed, setParsed] = useState(null);
  const [mapping, setMapping] = useState({});
  const [options, setOptions] = useState({ auto_account_numbers: true, separator: "-" });
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [mappingName, setMappingName] = useState("");

  const [inspectFile, { isLoading: inspecting }] = useInspectImportFileMutation();
  const [validateImport, { isLoading: validating }] = useValidateImportMutation();
  const [commitImport, { isLoading: committing }] = useCommitImportMutation();
  const { data: savedData } = useGetImportMappingsQuery(entity);
  const [saveMapping] = useSaveImportMappingMutation();
  const [deleteMapping] = useDeleteImportMappingMutation();

  const saved = savedData?.mappings ?? [];
  const spec = useMemo(
    () => (catalogue?.entities ?? []).find((e) => e.key === entity),
    [catalogue, entity]
  );
  // Memoised because `?? []` would hand back a fresh array every render, which
  // makes every downstream useMemo depending on it recompute for nothing.
  const fields = useMemo(() => spec?.fields ?? [], [spec]);

  // Switching entity restarts the wizard — a mapping for units means nothing
  // for tenants, and carrying one across silently maps the wrong columns.
  //
  // Done in the change handler rather than an effect on `entity`: resetting
  // from an effect renders the new tab once with the OLD tab's file and mapping
  // still on screen before wiping them, which is exactly the moment somebody
  // clicks "Read the file".
  const switchEntity = (next) => {
    setEntity(next);
    setStep(0);
    setFile(null);
    setParsed(null);
    setMapping({});
    setPreview(null);
    setResult(null);
  };

  const missingRequired = useMemo(
    () => fields.filter((f) => f.required && !mapping[f.key]).map((f) => f.label),
    [fields, mapping]
  );

  const handleUpload = async () => {
    if (!file) return;
    try {
      const data = await inspectFile({ entity, file }).unwrap();
      setParsed(data);
      setMapping(data.suggested_mapping || {});
      setStep(1);
    } catch (err) {
      toast(err?.data?.message || "Could not read that file.", { type: "error" });
    }
  };

  const handlePreview = async () => {
    try {
      const data = await validateImport({
        entity, rows: parsed.rows, mapping, options,
      }).unwrap();
      setPreview(data);
      setStep(2);
    } catch (err) {
      toast(err?.data?.message || "Could not check that file.", { type: "error" });
    }
  };

  const handleCommit = async () => {
    try {
      const data = await commitImport({
        entity, rows: parsed.rows, mapping, options,
      }).unwrap();
      setResult(data);
      setStep(3);
      toast(`${data.created} ${entity} imported.`, { type: "success" });
    } catch (err) {
      toast(err?.data?.message || "The import failed.", { type: "error" });
    }
  };

  const handleSaveMapping = async () => {
    const name = mappingName.trim();
    if (!name) return;
    try {
      await saveMapping({ entity, name, mapping, options }).unwrap();
      setMappingName("");
      toast(`Mapping "${name}" saved — pick it next time.`, { type: "success" });
    } catch {
      toast("Could not save the mapping.", { type: "error" });
    }
  };

  return (
    <div>
      <PageHeader
        title="Bulk import"
        subtitle="Bring properties, units and tenants in from a spreadsheet"
      />

      <Tabs
        tabs={entities.map((e) => ({ key: e.key, label: e.label }))}
        activeKey={entity}
        onChange={switchEntity}
        className="mb-5"
      />

      {spec && (
        <p className="mb-5 flex items-start gap-2 text-sm text-white/50">
          <Info className="mt-0.5 h-4 w-4 flex-shrink-0" />
          <span>
            <strong className="text-white/70">Step {spec.order} of 3.</strong> {spec.hint}
          </span>
        </p>
      )}

      <StepBar step={step} />

      {/* ---------------------------------------------------------------- */}
      {step === 0 && (
        <div className="glass space-y-4 p-5 sm:p-6">
          <FileUpload
            label="Spreadsheet"
            accept=".csv,.xlsx,.xlsm,.xls"
            hint="CSV or Excel. Your own column names are fine — you'll match them up next."
            value={file}
            onChange={setFile}
          />
          <Button onClick={handleUpload} isLoading={inspecting} disabled={!file}
                  leftIcon={<Upload className="h-4 w-4" />}>
            Read the file
          </Button>
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {step === 1 && parsed && (
        <div className="space-y-5">
          <div className="glass p-5 sm:p-6">
            <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
              <p className="text-sm text-white/60">
                {parsed.row_count} row{parsed.row_count === 1 ? "" : "s"} found.
                Match each field to a column from your file.
              </p>
              {saved.length > 0 && (
                <div className="flex items-center gap-2">
                  <Select
                    value=""
                    onChange={(e) => {
                      const found = saved.find((m) => String(m.id) === e.target.value);
                      if (!found) return;
                      setMapping(found.mapping || {});
                      setOptions({ ...options, ...(found.options || {}) });
                      toast(`Loaded "${found.name}".`, { type: "info" });
                    }}
                    options={[
                      { value: "", label: "Use a saved mapping…" },
                      ...saved.map((m) => ({ value: String(m.id), label: m.name })),
                    ]}
                  />
                </div>
              )}
            </div>

            <div className="space-y-3">
              {fields.map((field) => (
                <div key={field.key} className="grid grid-cols-1 gap-2 sm:grid-cols-2 sm:items-center">
                  <div>
                    <span className="text-sm text-white/80">
                      {field.label}
                      {field.required && <span className="ml-1 text-secondary">*</span>}
                    </span>
                    {field.help && (
                      <p className="text-xs leading-relaxed text-white/40">{field.help}</p>
                    )}
                  </div>
                  <Select
                    value={mapping[field.key] || ""}
                    onChange={(e) =>
                      setMapping((m) => ({ ...m, [field.key]: e.target.value || undefined }))
                    }
                    options={[
                      { value: "", label: "— not in my file —" },
                      ...parsed.headers.filter(Boolean).map((h) => ({ value: h, label: h })),
                    ]}
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Account-number generation. Only meaningful for units. */}
          {entity === "units" && (
            <div className="glass space-y-3 p-5 sm:p-6">
              <h3 className="text-sm font-medium text-white/80">Account numbers</h3>
              <p className="text-xs leading-relaxed text-white/40">
                This is what a tenant quotes when they pay, so every unit needs its
                own — across your whole account, not just within one block. Any
                clash is reported before anything is written.
              </p>
              <Checkbox
                label="Generate one for units with no account number in the file"
                checked={!!options.auto_account_numbers}
                onChange={(e) =>
                  setOptions((o) => ({ ...o, auto_account_numbers: e.target.checked }))
                }
              />
              {options.auto_account_numbers && (
                <div className="max-w-xs">
                  <Input
                    label="Separator"
                    value={options.separator ?? "-"}
                    maxLength={1}
                    hint="Composed as PROPERTY + separator + unit, e.g. KC-A1."
                    onChange={(e) => setOptions((o) => ({ ...o, separator: e.target.value }))}
                  />
                </div>
              )}
            </div>
          )}

          <div className="glass flex flex-wrap items-end gap-3 p-5 sm:p-6">
            <div className="min-w-[14rem] flex-1">
              <Input
                label="Save this mapping (optional)"
                placeholder="e.g. Monthly rent roll"
                hint="Reuse it next time instead of matching the columns again."
                value={mappingName}
                onChange={(e) => setMappingName(e.target.value)}
              />
            </div>
            <Button variant="ghost" onClick={handleSaveMapping} disabled={!mappingName.trim()}
                    leftIcon={<Save className="h-4 w-4" />}>
              Save mapping
            </Button>
          </div>

          {missingRequired.length > 0 && (
            <p className="flex items-center gap-2 text-sm text-amber-300/80">
              <AlertTriangle className="h-4 w-4" />
              Still to match: {missingRequired.join(", ")}
            </p>
          )}

          <div className="flex flex-wrap gap-2">
            <Button variant="ghost" onClick={() => setStep(0)}
                    leftIcon={<ArrowLeft className="h-4 w-4" />}>
              Back
            </Button>
            <Button onClick={handlePreview} isLoading={validating}
                    disabled={missingRequired.length > 0}
                    leftIcon={<ArrowRight className="h-4 w-4" />}>
              Check the file
            </Button>
          </div>
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {step === 2 && preview && (
        <div className="space-y-5">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <Summary label="Rows" value={preview.summary.total} />
            <Summary label="Will import" value={preview.summary.valid} tone="good" />
            <Summary label="Rejected" value={preview.summary.invalid} tone="bad" />
            <Summary label="With warnings" value={preview.summary.warnings} tone="warn" />
          </div>

          <PreviewTable rows={preview.rows} fields={fields} />

          <div className="flex flex-wrap gap-2">
            <Button variant="ghost" onClick={() => setStep(1)}
                    leftIcon={<ArrowLeft className="h-4 w-4" />}>
              Back to mapping
            </Button>
            <Button onClick={handleCommit} isLoading={committing}
                    disabled={preview.summary.valid === 0}>
              Import {preview.summary.valid} row{preview.summary.valid === 1 ? "" : "s"}
            </Button>
          </div>
          {preview.summary.invalid > 0 && (
            <p className="text-xs text-white/40">
              Rejected rows are skipped — the rest still import. Fix them in your
              file and run it again; anything already imported is recognised and
              not duplicated.
            </p>
          )}
        </div>
      )}

      {/* ---------------------------------------------------------------- */}
      {step === 3 && result && (
        <div className="glass space-y-4 p-6">
          <div className="flex items-center gap-3">
            <CheckCircle2 className="h-6 w-6 text-emerald-400" />
            <div>
              <p className="text-white">
                {result.created} {spec?.label.toLowerCase()} imported.
              </p>
              <p className="text-sm text-white/50">
                {result.skipped} already present, {result.rejected} rejected.
              </p>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="ghost" onClick={() => setStep(0)}>Import another file</Button>
            {spec?.order < 3 && (
              <Button
                onClick={() => switchEntity(entities.find((e) => e.order === spec.order + 1)?.key)}
              >
                Next: {entities.find((e) => e.order === spec.order + 1)?.label}
              </Button>
            )}
          </div>
        </div>
      )}

      {saved.length > 0 && step === 1 && (
        <div className="mt-6">
          <h3 className="mb-2 text-xs uppercase tracking-wide text-white/40">Saved mappings</h3>
          <ul className="flex flex-wrap gap-2">
            {saved.map((m) => (
              <li key={m.id} className="flex items-center gap-1 rounded-lg bg-white/5 px-3 py-1.5 text-sm text-white/70">
                {m.name}
                <button
                  onClick={() => deleteMapping(m.id)}
                  aria-label={`Delete mapping ${m.name}`}
                  className="ml-1 text-white/30 hover:text-secondary"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

function Summary({ label, value, tone }) {
  const colour =
    tone === "good" ? "text-emerald-400"
    : tone === "bad" ? "text-secondary"
    : tone === "warn" ? "text-amber-300"
    : "text-white";
  return (
    <div className="glass px-4 py-3">
      <p className="text-xs uppercase tracking-wide text-white/40">{label}</p>
      <p className={`text-xl ${colour}`}>{value}</p>
    </div>
  );
}

/**
 * Every row, with its own reason when there is one.
 *
 * Showing only the failures would hide what is ABOUT to be written, which is
 * the thing worth checking before importing four hundred units.
 */
function PreviewTable({ rows, fields }) {
  if (!rows.length) return <EmptyState title="Nothing to preview" />;

  // Keep the table readable: the identifying columns, not all fifteen.
  const shown = fields.slice(0, 4);

  return (
    <div className="glass overflow-x-auto">
      <table className="w-full text-left text-sm">
        <thead>
          <tr className="border-b border-white/10 text-white/40">
            <th className="px-3 py-2 font-medium">Row</th>
            {shown.map((f) => (
              <th key={f.key} className="px-3 py-2 font-medium">{f.label}</th>
            ))}
            <th className="px-3 py-2 font-medium">Status</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr
              key={row._line}
              className={
                row.errors.length
                  ? "border-b border-white/5 bg-secondary/5"
                  : "border-b border-white/5"
              }
            >
              <td className="px-3 py-2 text-white/40">{row._line}</td>
              {shown.map((f) => (
                <td key={f.key} className="px-3 py-2 text-white/80">
                  {String(row.values[f.key] ?? "")}
                </td>
              ))}
              <td className="px-3 py-2">
                {row.errors.length > 0 ? (
                  <div className="space-y-1">
                    <Badge color="secondary">Rejected</Badge>
                    {row.errors.map((e, i) => (
                      <p key={i} className="text-xs leading-relaxed text-secondary-300">{e}</p>
                    ))}
                  </div>
                ) : row.warnings.length > 0 ? (
                  <div className="space-y-1">
                    <Badge color="white">Check</Badge>
                    {row.warnings.map((w, i) => (
                      <p key={i} className="text-xs leading-relaxed text-amber-300/80">{w}</p>
                    ))}
                  </div>
                ) : (
                  <Badge color="third">Ready</Badge>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
