"""
SahilPay — services/pdf_service.py
=====================================
WeasyPrint-backed PDF generation. All HTML is built inline (simple,
genuinely-rendered documents) rather than via Jinja2 template files — no
templates/ directory exists yet, and these are small enough to compose
directly. Every function returns raw PDF bytes; routes decide whether to
stream, email, or upload them.
"""

from __future__ import annotations

from datetime import date
from html import escape

from utils import render_pdf
from services import branding

_BASE_STYLE = """
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a2e; font-size: 13px; }
  h1 { font-size: 20px; font-weight: 300; margin-bottom: 4px; }
  h2 { font-size: 15px; font-weight: 500; margin-top: 24px; margin-bottom: 8px; }
  .muted { color: #6b6b80; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e2e2e8; font-size: 12px; }
  th { background: #f4f4f8; font-weight: 600; }
  .total-row td { font-weight: 700; border-top: 2px solid #1a1a2e; }
  .header { display: flex; justify-content: space-between; border-bottom: 2px solid #200497; padding-bottom: 12px; margin-bottom: 16px; }
</style>
"""


def _money(value) -> str:
    try:
        return f"KES {float(value):,.2f}"
    except (TypeError, ValueError):
        return "KES 0.00"


def _generated_by_html() -> str:
    """Subtle 'generated by' credit for landlord-issued documents — never
    competes with the landlord's own identity above it."""
    return (
        "<div style='margin-top:24px;padding-top:8px;border-top:1px solid #e2e2e8;"
        "font-size:9px;color:#6b6b80;display:flex;align-items:center;gap:5px;'>"
        f"{branding.logo_mark_svg(color=branding.BRAND_MUTED, size=14)}"
        f"<span>Generated by {branding.BRAND_NAME} &middot; {branding.BRAND_WEBSITE.replace('https://', '')} &middot; {branding.BRAND_PHONE}</span>"
        "</div>"
    )


def _shell(title: str, body_html: str) -> str:
    return f"<!doctype html><html><head><meta charset='utf-8'>{_BASE_STYLE}</head><body><h1>{escape(title)}</h1>{body_html}{_generated_by_html()}</body></html>"


def _landlord_document(landlord, *, title: str, body_html: str, subject: str | None = None,
                       property_name: str | None = None, period: str | None = None,
                       signature: bool = True) -> str:
    """
    A landlord-issued document in the landlord's identity: their letterhead,
    logo, contact details and theme colours, ruled-grid tables, their signature
    and the small generated-by credit. The same frame every report uses, so an
    invoice, a statement and a report from one account look like one set.
    """
    from services.report_builder import (
        _letterhead_html, _platform_credit_html, _signature_html, build_meta, report_style,
    )

    meta = build_meta(landlord, report_title=title, subject=subject,
                      property_name=property_name, period=period)
    sig = _signature_html(meta) if signature else ""
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"{report_style(meta.get('theme'))}</head><body>"
        f"{_letterhead_html(meta)}{body_html}{sig}{_platform_credit_html()}"
        "</body></html>"
    )


def generate_invoice_pdf(invoice) -> bytes:
    """Render a single invoice (details + line items + totals) as ruled tables."""
    tenant = invoice.tenant
    landlord = invoice.landlord
    unit_name = invoice.unit.name if invoice.unit else ""
    prop_name = invoice.unit.property.name if invoice.unit and invoice.unit.property else None
    rows = "".join(
        f"<tr><td>{escape(li.item)}</td><td>{escape(li.description or '')}</td>"
        f"<td class='right'>{li.quantity}</td><td class='right'>{_money(li.unit_price)}</td>"
        f"<td class='right'>{_money(li.amount)}</td></tr>"
        for li in invoice.line_items
    )
    body = f"""
    <h2>Invoice details</h2>
    <table class="grid kv"><tbody>
      <tr><td>Invoice number</td><td>{escape(invoice.invoice_number)}</td></tr>
      <tr><td>Billed to</td><td>{escape(tenant.first_name)} {escape(tenant.last_name)}</td></tr>
      <tr><td>Unit</td><td>{escape(unit_name)}{(' — ' + escape(prop_name)) if prop_name else ''}</td></tr>
      <tr><td>Issue date</td><td>{invoice.issue_date}</td></tr>
      <tr><td>Due date</td><td>{invoice.due_date or '—'}</td></tr>
    </tbody></table>
    <h2>Charges</h2>
    <table class="grid">
      <thead><tr><th>Item</th><th>Description</th><th class="right">Qty</th><th class="right">Unit price</th><th class="right">Amount</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
    <h2>Summary</h2>
    <table class="grid kv"><tbody>
      <tr><td>Total</td><td class="right">{_money(invoice.total_amount)}</td></tr>
      <tr><td>Paid</td><td class="right">{_money(invoice.amount_paid)}</td></tr>
      <tr class="total-row"><td>Balance due</td><td class="right">{_money(invoice.balance)}</td></tr>
    </tbody></table>
    """
    return render_pdf(_landlord_document(
        landlord, title=invoice.title or f"Invoice {invoice.invoice_number}", body_html=body,
        subject=f"{tenant.first_name} {tenant.last_name} · Unit {unit_name}", property_name=prop_name,
    ))


def generate_receipt_pdf(payment) -> bytes:
    """Render a payment receipt to PDF (the full itemised receipt lives in receipt_service)."""
    landlord = payment.landlord
    tenant = payment.tenant
    name = f"{tenant.first_name} {tenant.last_name}" if tenant else "N/A"
    body = f"""
    <table class="grid kv"><tbody>
      <tr><td>Receipt number</td><td>{escape(payment.payment_ref)}</td></tr>
      <tr><td>Date</td><td>{payment.payment_date}</td></tr>
      <tr><td>Received from</td><td>{escape(name)}</td></tr>
      <tr><td>Method</td><td>{escape(payment.payment_method or payment.source or '—')}</td></tr>
      <tr><td>Reference</td><td>{escape(payment.mpesa_reference or payment.payment_ref)}</td></tr>
      <tr><td>Status</td><td>{escape(payment.status or '')}</td></tr>
      <tr class="total-row"><td>Amount</td><td class="right">{_money(payment.amount)}</td></tr>
    </tbody></table>
    <p class="muted">Thank you for your payment.</p>
    """
    return render_pdf(_landlord_document(landlord, title="Payment Receipt", body_html=body, subject=name))


def _subscription_etims_html(transaction, landlord) -> str:
    """
    The eTIMS block on a SahilPay subscription / SMS receipt (spec §3.4).

    Returns "" unless a System Admin has recorded a number against this
    transaction. Deliberately NOT gated on any landlord's per-property setting:
    the seller on this document is SahilPay, so it is SahilPay's own compliance
    posture — expressed through the platform kill switch and the platform PIN —
    that decides, not the customer's.
    """
    from services import etims_service as etims
    from services.etims_pdf import qr_data_uri

    if not getattr(transaction, "etims_invoice_number", None):
        return ""
    try:
        if not etims.features_enabled():
            return ""
        platform_pin = etims.platform_settings().kra_pin
    except Exception:
        return ""

    lines = []
    if platform_pin:
        lines.append(f"<tr><td>SahilPay KRA PIN</td><td>{escape(platform_pin)}</td></tr>")
    client_pin = getattr(landlord.user, "kra_pin", None) if landlord and landlord.user else None
    if client_pin:
        lines.append(f"<tr><td>Your KRA PIN</td><td>{escape(client_pin)}</td></tr>")
    issued_at = ""
    if transaction.etims_issued_at:
        issued_at = f" &middot; issued {transaction.etims_issued_at.strftime('%d %b %Y')}"
    lines.append(
        f"<tr><td>eTIMS invoice no.</td><td>"
        f"{escape(transaction.etims_invoice_number)}{issued_at}</td></tr>"
    )

    qr = qr_data_uri(transaction.etims_qr_url)
    qr_html = (f"<div style='margin-top:8px;'><img src='{qr}' alt='KRA verification QR' "
               f"style='width:22mm;height:22mm;'/></div>") if qr else ""

    return (f"<table class='block'><tbody>{''.join(lines)}</tbody></table>{qr_html}")


def _platform_document(*, title: str, meta_rows: list[tuple[str, str]], body_html: str) -> str:
    """
    A document Sahil Pay issues as ITSELF (subscription and SMS receipts): the
    Sahil Pay letterhead with the full lockup, registered contact details, and
    the same ruled-grid tables landlords' documents use — in Sahil colours.
    """
    from services.report_builder import report_style

    meta_html = "".join(
        f"<tr><td>{escape(k)}</td><td class='right'>{v}</td></tr>" for k, v in meta_rows
    )
    return f"""<!doctype html><html><head><meta charset='utf-8'>{report_style(None)}
    <style>
      .sp-head {{ display:flex; justify-content:space-between; align-items:flex-start;
                  border-bottom: 3px solid {branding.BRAND_VIOLET}; padding-bottom: 12px; }}
      .sp-contact {{ font-size: 10.5px; color: {branding.BRAND_MUTED}; line-height: 1.55; margin-top: 8px; }}
      .sp-title {{ font-size: 22px; font-weight: 600; color: {branding.BRAND_NAVY}; margin: 16px 0 4px; letter-spacing:.02em; }}
      .sp-meta {{ width: 46%; }}
      .sp-meta table {{ margin-top: 0; }}
      .stamp {{ display:inline-block; padding: 5px 14px; border-radius: 999px; font-weight: 700;
                font-size: 11px; letter-spacing: .08em; }}
      .stamp.paid {{ background:#e6f7ef; color:#0f7a4d; border:1px solid #0f7a4d; }}
      .stamp.pending {{ background:#fff6e5; color:#9a5b00; border:1px solid #9a5b00; }}
      .stamp.failed {{ background:#fdeceb; color:#b5382f; border:1px solid #b5382f; }}
      .foot {{ margin-top: 22px; font-size: 10.5px; color: {branding.BRAND_MUTED}; }}
    </style></head><body>
    <div class="sp-head">
      <div>
        {branding.logo_lockup_html()}
        <div class="sp-contact">
          {branding.BRAND_LOCATION}<br/>
          Tel: {branding.BRAND_PHONE} &middot; {branding.BRAND_EMAIL}<br/>
          {branding.BRAND_WEBSITE.replace('https://', '')}
        </div>
      </div>
      <div class="sp-meta"><table class="grid kv"><tbody>{meta_html}</tbody></table></div>
    </div>
    <div class="sp-title">{escape(title)}</div>
    {body_html}
    {branding.pdf_footer_html()}
    </body></html>"""


def generate_tax_invoice_pdf(transaction, landlord) -> bytes:
    """
    The Sahil Pay receipt for a platform charge (subscription or SMS credits).

    Only a VERIFIED transaction is issued as PAID — the route refuses anything
    else — but the stamp still reads the real status so a copy can never claim
    more than the ledger does. VAT is shown inclusive (Kenya standard rate 16%).
    """
    from decimal import Decimal, ROUND_HALF_UP

    ctx = dict(transaction.context_json or {})
    if transaction.type == "sms_purchase":
        line_desc = f"SMS credits — {transaction.sms_count or 0:,} messages"
        if ctx.get("unit_price"):
            line_desc += f" at KES {Decimal(str(ctx['unit_price'])):,.2f} each"
    else:
        line_desc = "Sahil Pay subscription — platform fee"
        if ctx.get("mode") == "balance":
            line_desc = "Sahil Pay subscription — payment towards account balance"
        if ctx.get("billing_cycle") and ctx.get("mode") != "balance":
            line_desc += f" ({ctx['billing_cycle']})"

    gross = Decimal(str(transaction.amount or 0))
    net = (gross / Decimal("1.16")).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
    vat = gross - net

    from datetime import timedelta
    paid_on = transaction.verified_at or transaction.created_at
    # Stored in UTC; a Kenyan receipt reads in East Africa Time.
    issued = (paid_on + timedelta(hours=3)).strftime("%d %b %Y, %H:%M EAT") if paid_on else "—"
    receipt_no = f"SP-RCPT-{transaction.id:06d}"
    status = (transaction.status or "pending").lower()
    stamp_class = {"paid": "paid", "failed": "failed"}.get(status, "pending")
    stamp = f"<span class='stamp {stamp_class}'>{escape(status.upper())}</span>"

    etims_html = _subscription_etims_html(transaction, landlord)
    contact = ""
    try:
        from services.document_brand import contact_for
        c = contact_for(landlord)
        contact = " · ".join(p for p in (c["phone"], c["email"]) if p)
    except Exception:  # pragma: no cover - a receipt must render regardless
        pass

    balance_rows = ""
    if ctx.get("balance_before") is not None and ctx.get("balance_after") is not None:
        before = Decimal(str(ctx["balance_before"]))
        after = Decimal(str(ctx["balance_after"]))
        after_label = "Credit carried forward" if after < 0 else "Balance remaining"
        balance_rows = f"""
    <h2>Account balance</h2>
    <table class="grid kv"><tbody>
      <tr><td>Balance before this payment</td><td class="right">{_money(before)}</td></tr>
      <tr><td>This payment</td><td class="right">-{_money(gross)}</td></tr>
      <tr class="total-row"><td>{after_label}</td><td class="right">{_money(abs(after))}</td></tr>
    </tbody></table>"""

    body = f"""
    <div style="margin: 4px 0 12px;">{stamp}</div>
    <h2>Billed to</h2>
    <table class="grid kv"><tbody>
      <tr><td>Account</td><td>{escape(landlord.company_name)}</td></tr>
      <tr><td>Address</td><td>{escape(landlord.company_address or '—')}</td></tr>
      <tr><td>Contact</td><td>{escape(contact or '—')}</td></tr>
      <tr><td>Account number</td><td>{'SMS' if transaction.type == 'sms_purchase' else 'SUB'}-{landlord.id}</td></tr>
    </tbody></table>

    <h2>Charges</h2>
    <table class="grid">
      <thead><tr><th>Description</th><th class="right">Amount</th></tr></thead>
      <tbody>
        <tr><td>{escape(line_desc)}</td><td class="right">{_money(net)}</td></tr>
        <tr><td>VAT (16%, inclusive)</td><td class="right">{_money(vat)}</td></tr>
        <tr class="total-row"><td>Total paid</td><td class="right">{_money(gross)}</td></tr>
      </tbody>
    </table>
    {balance_rows}
    <h2>Payment</h2>
    <table class="grid kv"><tbody>
      <tr><td>Method</td><td>M-Pesa Paybill {escape(str(ctx.get('shortcode') or '4326127'))}</td></tr>
      <tr><td>M-Pesa receipt</td><td>{escape(transaction.payment_reference or '—')}</td></tr>
      <tr><td>Paid from</td><td>{escape(str(ctx.get('payer_phone') or '—'))}</td></tr>
      <tr><td>Confirmed</td><td>{escape(issued)}{' — confirmed by M-Pesa' if transaction.is_verified else ''}</td></tr>
      <tr><td>Transaction ID</td><td>#{transaction.id}</td></tr>
    </tbody></table>

    {etims_html}

    <div class="foot">
      Thank you for choosing Sahil Pay. This receipt was generated after the payment was
      confirmed in the Sahil Pay paybill and is valid without a signature. Amounts are in
      KES and include VAT where applicable. Questions: {branding.BRAND_EMAIL} &middot; {branding.BRAND_PHONE}.
    </div>
    """
    return render_pdf(_platform_document(
        title="Payment Receipt",
        meta_rows=[("Receipt no.", f"<strong>{receipt_no}</strong>"), ("Date", escape(issued)),
                   ("Status", escape(status.title()))],
        body_html=body,
    ))


def generate_affiliate_receipt_pdf(withdrawal) -> bytes:
    """
    KRA-compliant affiliate commission payout receipt — gross / withholding
    tax / Sahil platform fee / net breakdown. Every figure is read from the
    withdrawal row's own snapshotted columns (never live config), so a
    receipt regenerated years later is byte-identical regardless of later
    rate changes (AFFILIATE_PROGRAM_SPEC.md D11/D7/E24).
    """
    affiliate = withdrawal.affiliate
    issued = withdrawal.processed_at.strftime("%d %b %Y") if withdrawal.processed_at else "—"
    fee_label = f"{withdrawal.fee_value}%" if withdrawal.fee_type == "percent" else _money(withdrawal.fee_value)

    style = """
    <style>
      .rcpt-title { text-align: right; }
      .rcpt-title h2 { color:#200497; margin:0 0 4px; font-size:18px; font-weight:600; }
      .block { margin-top: 18px; }
      .foot { margin-top: 28px; border-top: 1px solid #e2e2e8; padding-top: 12px; }
      .net-row td { font-weight: 700; border-top: 2px solid #1a1a2e; font-size: 14px; }
    </style>
    """

    body = f"""
    {style}
    {branding.pdf_header_html(
        document_label="Affiliate Program",
        meta_html=f"<h2 style='margin:0 0 4px;color:{branding.BRAND_VIOLET};font-size:18px;font-weight:600;'>Affiliate Commission Payout Receipt</h2>"
                  f"Receipt No: <strong>{escape(withdrawal.receipt_number or '—')}</strong><br/>Date paid: {issued}",
    )}

    <div class="block">
      <div class="muted">Paid to</div>
      <strong>{escape(affiliate.full_name)}</strong><br/>
      <span class="muted">National ID: {escape(affiliate.national_id or '—')}</span><br/>
      <span class="muted">KRA PIN: {escape(affiliate.kra_pin or '—')}</span><br/>
      <span class="muted">M-Pesa number: {escape(affiliate.mpesa_number or '—')}</span>
    </div>

    <table class="block">
      <thead><tr><th>Description</th><th style="text-align:right;">Amount</th></tr></thead>
      <tbody>
        <tr><td>Gross commission withdrawn</td><td style="text-align:right;">{_money(withdrawal.gross_amount)}</td></tr>
        <tr><td>Withholding tax ({withdrawal.wht_rate}%)</td><td style="text-align:right;">-{_money(withdrawal.wht_amount)}</td></tr>
        <tr><td>Sahil Pay platform fee ({fee_label})</td><td style="text-align:right;">-{_money(withdrawal.fee_amount)}</td></tr>
      </tbody>
      <tfoot>
        <tr class="net-row"><td>Net paid to affiliate</td><td style="text-align:right;">{_money(withdrawal.net_amount)}</td></tr>
      </tfoot>
    </table>

    <table class="block">
      <tbody>
        <tr><td>M-Pesa transaction reference</td><td>{escape(withdrawal.mpesa_reference or '—')}</td></tr>
        <tr><td>Withdrawal ID</td><td>#{withdrawal.id}</td></tr>
      </tbody>
    </table>

    <div class="foot muted">
      Withholding tax deducted at source and remitted to KRA by Sahil Pay. This is a
      system-generated receipt and is valid without a signature. Amounts are shown in KES.
    </div>
    {branding.pdf_footer_html()}
    """
    html = (
        f"<!doctype html><html><head><meta charset='utf-8'>{_BASE_STYLE}</head>"
        f"<body>{body}</body></html>"
    )
    return render_pdf(html)


def generate_tenant_statement_pdf(tenant) -> bytes:
    """
    A tenant's full running statement (invoices + payments, chronological) as
    one ruled table, in the landlord's identity.
    """
    landlord = tenant.landlord
    entries = []
    for inv in tenant.invoices:
        if getattr(inv, "is_deleted", False):
            continue
        entries.append((inv.issue_date, f"Invoice {inv.invoice_number}", inv.title or inv.invoice_type, inv.total_amount, 0))
    for pay in tenant.payments:
        entries.append((pay.payment_date, f"Payment {pay.payment_ref}",
                        pay.mpesa_reference or pay.payment_method or "", 0, pay.amount))
    entries.sort(key=lambda e: str(e[0] or ""))

    rows = ""
    running = 0.0
    total_due = total_paid = 0.0
    for d, label, detail, due, paid in entries:
        running += float(due or 0) - float(paid or 0)
        total_due += float(due or 0)
        total_paid += float(paid or 0)
        rows += (
            f"<tr><td>{d}</td><td>{escape(label)}</td><td>{escape(str(detail or ''))}</td>"
            f"<td class='right'>{_money(due) if due else '—'}</td>"
            f"<td class='right'>{_money(paid) if paid else '—'}</td>"
            f"<td class='right'>{_money(running)}</td></tr>"
        )
    rows += (f"<tr class='total-row'><td colspan='3'>Totals</td><td class='right'>{_money(total_due)}</td>"
             f"<td class='right'>{_money(total_paid)}</td><td class='right'>{_money(tenant.balance)}</td></tr>")

    unit = tenant.unit
    prop = unit.property if unit else None
    body = f"""
    <h2>Account</h2>
    <table class="grid kv"><tbody>
      <tr><td>Tenant</td><td>{escape(tenant.first_name)} {escape(tenant.last_name)}</td></tr>
      <tr><td>Unit</td><td>{escape(unit.name if unit else '—')}{(' — ' + escape(prop.name)) if prop else ''}</td></tr>
      <tr><td>Phone</td><td>{escape(tenant.phone or '—')}</td></tr>
      <tr class="total-row"><td>Current balance</td><td class="right">{_money(tenant.balance)}</td></tr>
    </tbody></table>
    <h2>Statement of account</h2>
    <table class="grid">
      <thead><tr><th>Date</th><th>Entry</th><th>Detail</th><th class="right">Charged</th><th class="right">Paid</th><th class="right">Balance</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
    """
    return render_pdf(_landlord_document(
        landlord, title="Tenant Statement", body_html=body,
        subject=f"{tenant.first_name} {tenant.last_name}", property_name=prop.name if prop else None,
        signature=False,
    ))


def generate_tenants_list_pdf(tenants: list) -> bytes:
    """A tenants directory (name, unit, phone, balance) as a ruled table."""
    rows = "".join(
        f"<tr><td>{escape(t.first_name)} {escape(t.last_name)}</td>"
        f"<td>{escape(t.unit.name if t.unit else '')}</td>"
        f"<td>{escape(t.phone or '')}</td><td class='right'>{_money(t.balance)}</td></tr>"
        for t in tenants
    )
    body = f"""
    <table class="grid">
      <thead><tr><th>Tenant</th><th>Unit</th><th>Phone</th><th class="right">Balance</th></tr></thead>
      <tbody>{rows}</tbody>
    </table>
    """
    landlord = tenants[0].landlord if tenants else None
    if landlord is None:
        return render_pdf(_shell("Tenants", body))
    return render_pdf(_landlord_document(landlord, title="Tenants", body_html=body, signature=False))


def render_document_template(html_body: str) -> bytes:
    """
    Wrap an already-rendered document body (placeholders already substituted
    by the caller) in a minimal HTML shell and convert to PDF. Used for
    dispatching lease/tenancy/deposit document templates to tenants.
    """
    return render_pdf(f"<!doctype html><html><head><meta charset='utf-8'>{_BASE_STYLE}</head><body>{html_body}</body></html>")
