"""add tenant_messages table

Revision ID: 425cd1d75fab
Revises: a1b2c3d4e5f6
Create Date: 2026-07-03 19:39:42.277199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425cd1d75fab'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=15), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_messages_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_messages_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_tenant_messages_thread', ['landlord_id', 'tenant_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_tenant_messages_thread')
        batch_op.drop_index(batch_op.f('ix_tenant_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_messages_landlord_id'))

    op.drop_table('tenant_messages')
    # ### end Alembic commands ###
