"""initial schema

Revision ID: 5d205659571c
Revises: 
Create Date: 2026-06-25 21:55:44.822028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d205659571c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_units', sa.Integer(), nullable=False),
    sa.Column('max_units', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flat_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(max_units IS NULL) OR (max_units >= min_units)', name='ck_packages_max_gte_min'),
    sa.CheckConstraint('(price_per_unit IS NOT NULL) OR (flat_price IS NOT NULL)', name='ck_packages_at_least_one_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(role = 'tenant') OR (password_hash IS NOT NULL)", name='ck_users_non_tenant_needs_password'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    op.create_table('landlords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('abbreviated_name', sa.String(length=100), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('signature_url', sa.String(length=255), nullable=True),
    sa.Column('invoice_title', sa.String(length=150), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('mpesa_type', sa.String(length=20), nullable=True),
    sa.Column('mpesa_number', sa.String(length=20), nullable=True),
    sa.Column('default_account_number', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=True),
    sa.Column('default_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('agent_code', sa.String(length=50), nullable=True),
    sa.Column('sms_balance', sa.Integer(), nullable=False),
    sa.Column('per_unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_on_trial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(mpesa_type IS NULL) OR (mpesa_number IS NOT NULL)', name='ck_landlords_mpesa_number_required'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code')
    )
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlords_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_landlords_user_id'), ['user_id'], unique=True)

    op.create_table('otp_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_otp_tokens_identifier_is_used', ['identifier', 'is_used'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('system_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_admins_user_id'), ['user_id'], unique=True)

    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('cadence', sa.String(length=10), nullable=True),
    sa.Column('channel', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'alert_type', name='uq_alert_settings_landlord_type')
    )
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_settings_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_username', sa.String(length=150), nullable=True),
    sa.Column('actor_full_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('affected_properties', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_landlord_created_at', ['landlord_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('automation_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('auto_generate_recurring_invoices', sa.Boolean(), nullable=False),
    sa.Column('auto_generate_recurring_bills', sa.Boolean(), nullable=False),
    sa.Column('alert_on_new_tenant', sa.Boolean(), nullable=False),
    sa.Column('auto_send_payment_acknowledgments', sa.Boolean(), nullable=False),
    sa.Column('monthly_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('monthly_reminder_day', sa.Integer(), nullable=True),
    sa.Column('lease_expiry_notifications', sa.Boolean(), nullable=False),
    sa.Column('lease_expiry_range_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_settings_landlord_id'), ['landlord_id'], unique=True)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=True),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('bank_statement_uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statement_uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_uploads_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('billing_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sms_count', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('tax_invoice_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_transactions_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('impersonation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impersonation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impersonation_requests_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impersonation_requests_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('landlord_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('low_sms_balance_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_settings_landlord_id'), ['landlord_id'], unique=True)

    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('template_type', sa.String(length=30), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_templates_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('property_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_groups_landlord_id'), ['landlord_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=15), nullable=True),
    sa.Column('unit_count', sa.Integer(), nullable=False),
    sa.Column('subscription_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_landlord_id'), ['landlord_id'], unique=True)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('property_access_all', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=True)

    op.create_table('trial_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=15), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', name='uq_trial_configs_landlord')
    )
    with op.batch_alter_table('trial_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_configs_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index('ix_trial_configs_single_global', ['scope'], unique=True, postgresql_where=sa.text("scope = 'global'"))

    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('number_of_units', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('street_name', sa.String(length=200), nullable=True),
    sa.Column('water_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('electricity_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mpesa_details', sa.String(length=50), nullable=True),
    sa.Column('rent_payment_penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('management_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_group_id'], ['property_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_property_group_id'), ['property_group_id'], unique=False)

    op.create_table('team_member_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=30), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_member_id', 'module', name='uq_tmp_team_member_module')
    )
    with op.batch_alter_table('team_member_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_permissions_team_member_id'), ['team_member_id'], unique=False)

    op.create_table('team_member_property_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_member_id', 'property_id', name='uq_tmpa_member_property')
    )
    with op.batch_alter_table('team_member_property_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_property_access_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_member_property_access_team_member_id'), ['team_member_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'name', name='uq_units_property_name')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_property_id'), ['property_id'], unique=False)

    op.create_table('manager_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=15), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('property_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('\n            (\n              (unit_id IS NOT NULL AND property_id IS NULL AND property_group_id IS NULL) OR\n              (unit_id IS NULL AND property_id IS NOT NULL AND property_group_id IS NULL) OR\n              (unit_id IS NULL AND property_id IS NULL AND property_group_id IS NOT NULL)\n            )\n            ', name='ck_manager_assignments_exactly_one_scope'),
    sa.ForeignKeyConstraint(['property_group_id'], ['property_groups.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manager_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manager_assignments_property_group_id'), ['property_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manager_assignments_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manager_assignments_team_member_id'), ['team_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manager_assignments_unit_id'), ['unit_id'], unique=False)

    op.create_table('recurring_bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(property_id IS NOT NULL) OR (unit_id IS NOT NULL)', name='ck_recurring_bills_property_or_unit'),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_bills_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_bills_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_bills_unit_id'), ['unit_id'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expenses_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_expenses_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_expenses_unit_id'), ['unit_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('kra_pin', sa.String(length=30), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deposit_returned', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rent_payment_penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bank_payer_name', sa.String(length=150), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lease_start_date', sa.Date(), nullable=True),
    sa.Column('lease_expiry_date', sa.Date(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'account_number', name='uq_tenants_landlord_account')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_user_id'), ['user_id'], unique=False)

    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=True),
    sa.Column('recipient_type', sa.String(length=15), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sms_charge', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('provider_message_id', sa.String(length=80), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_logs_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_team_member_id'), ['team_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_unit_id'), ['unit_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=True),
    sa.Column('recurring_expense_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], name='fk_expenses_maintenance_request_id', use_alter=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_maintenance_request_id'), ['maintenance_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_recurring_expense_id'), ['recurring_expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_unit_id'), ['unit_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'invoice_number', name='uq_invoices_landlord_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_unit_id'), ['unit_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_ref', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('mpesa_reference', sa.String(length=40), nullable=True),
    sa.Column('till_number', sa.String(length=20), nullable=True),
    sa.Column('bank_statement_id', sa.Integer(), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statement_uploads.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('landlord_id', 'payment_ref', name='uq_payments_landlord_ref')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bank_statement_id'), ['bank_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_mpesa_reference'), ['mpesa_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_ref'), ['payment_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_unit_id'), ['unit_id'], unique=False)

    op.create_table('tenant_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_unit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('moved_in_at', sa.Date(), nullable=False),
    sa.Column('moved_out_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_unit_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_unit_history_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_unit_history_unit_id'), ['unit_id'], unique=False)

    op.create_table('bank_statement_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_statement_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('matched_payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statement_uploads.id'], ),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statement_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_transactions_bank_statement_id'), ['bank_statement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bank_statement_transactions_matched_payment_id'), ['matched_payment_id'], unique=False)

    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_requests_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_unit_id'), ['unit_id'], unique=False)

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=40), nullable=False),
    sa.Column('shortcode', sa.String(length=20), nullable=True),
    sa.Column('till_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_reference_number'), ['reference_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_allocated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount_allocated > 0', name='ck_payment_allocations_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'invoice_id', name='uq_payment_allocations_payment_invoice')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)

    op.create_table('utility_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('utility_item', sa.String(length=20), nullable=False),
    sa.Column('previous_reading', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_reading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('consumption', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reading_month', sa.String(length=7), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(previous_reading IS NULL) OR (current_reading >= previous_reading)', name='ck_utility_readings_current_gte_previous'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'utility_item', 'reading_month', name='uq_utility_readings_unit_item_month')
    )
    with op.batch_alter_table('utility_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utility_readings_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_readings_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_readings_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_utility_readings_unit_id'), ['unit_id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('utility_reading_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['utility_reading_id'], ['utility_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_utility_reading_id'), ['utility_reading_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_utility_reading_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('utility_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utility_readings_unit_id'))
        batch_op.drop_index(batch_op.f('ix_utility_readings_property_id'))
        batch_op.drop_index(batch_op.f('ix_utility_readings_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_utility_readings_invoice_id'))

    op.drop_table('utility_readings')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_invoice_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_reference_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_payment_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_landlord_id'))

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_unit_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_property_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_expense_id'))

    op.drop_table('maintenance_requests')
    with op.batch_alter_table('bank_statement_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_transactions_matched_payment_id'))
        batch_op.drop_index(batch_op.f('ix_bank_statement_transactions_bank_statement_id'))

    op.drop_table('bank_statement_transactions')
    with op.batch_alter_table('tenant_unit_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_unit_history_unit_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_unit_history_tenant_id'))

    op.drop_table('tenant_unit_history')
    with op.batch_alter_table('tenant_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_documents_tenant_id'))

    op.drop_table('tenant_documents')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_unit_id'))
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_property_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_ref'))
        batch_op.drop_index(batch_op.f('ix_payments_mpesa_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_payments_bank_statement_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_unit_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_property_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))

    op.drop_table('invoices')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_unit_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_recurring_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_property_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_maintenance_request_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_landlord_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_logs_unit_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_team_member_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_property_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_landlord_id'))

    op.drop_table('communication_logs')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_unit_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_phone'))
        batch_op.drop_index(batch_op.f('ix_tenants_landlord_id'))

    op.drop_table('tenants')
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_unit_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_property_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_landlord_id'))

    op.drop_table('recurring_expenses')
    with op.batch_alter_table('recurring_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_bills_unit_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_bills_property_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_bills_landlord_id'))

    op.drop_table('recurring_bills')
    with op.batch_alter_table('manager_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manager_assignments_unit_id'))
        batch_op.drop_index(batch_op.f('ix_manager_assignments_team_member_id'))
        batch_op.drop_index(batch_op.f('ix_manager_assignments_property_id'))
        batch_op.drop_index(batch_op.f('ix_manager_assignments_property_group_id'))

    op.drop_table('manager_assignments')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_property_id'))

    op.drop_table('units')
    with op.batch_alter_table('team_member_property_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_property_access_team_member_id'))
        batch_op.drop_index(batch_op.f('ix_team_member_property_access_property_id'))

    op.drop_table('team_member_property_access')
    with op.batch_alter_table('team_member_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_permissions_team_member_id'))

    op.drop_table('team_member_permissions')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_property_group_id'))
        batch_op.drop_index(batch_op.f('ix_properties_landlord_id'))

    op.drop_table('properties')
    with op.batch_alter_table('trial_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_trial_configs_single_global', postgresql_where=sa.text("scope = 'global'"))
        batch_op.drop_index(batch_op.f('ix_trial_configs_landlord_id'))

    op.drop_table('trial_configs')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_landlord_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_landlord_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('property_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_groups_landlord_id'))

    op.drop_table('property_groups')
    with op.batch_alter_table('message_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_templates_landlord_id'))

    op.drop_table('message_templates')
    with op.batch_alter_table('landlord_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_settings_landlord_id'))

    op.drop_table('landlord_settings')
    with op.batch_alter_table('impersonation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impersonation_requests_landlord_id'))
        batch_op.drop_index(batch_op.f('ix_impersonation_requests_admin_user_id'))

    op.drop_table('impersonation_requests')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_landlord_id'))

    op.drop_table('document_templates')
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_transactions_landlord_id'))

    op.drop_table('billing_transactions')
    with op.batch_alter_table('bank_statement_uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_statement_uploads_landlord_id'))

    op.drop_table('bank_statement_uploads')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_landlord_id'))

    op.drop_table('backups')
    with op.batch_alter_table('automation_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_settings_landlord_id'))

    op.drop_table('automation_settings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_landlord_id'))
        batch_op.drop_index('ix_audit_logs_landlord_created_at')
        batch_op.drop_index('ix_audit_logs_entity_type_entity_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alert_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_settings_landlord_id'))

    op.drop_table('alert_settings')
    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_admins_user_id'))

    op.drop_table('system_admins')
    with op.batch_alter_table('otp_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_tokens_user_id'))
        batch_op.drop_index('ix_otp_tokens_identifier_is_used')

    op.drop_table('otp_tokens')
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlords_user_id'))
        batch_op.drop_index(batch_op.f('ix_landlords_package_id'))

    op.drop_table('landlords')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    op.drop_table('packages')
    # ### end Alembic commands ###
