"""mpesa production integration

Revision ID: 70d7e5498282
Revises: a7b8c9d0e1f2
Create Date: 2026-07-15 20:27:18.655354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70d7e5498282'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daraja_callback_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daraja_callback_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daraja_callback_logs_kind'), ['kind'], unique=False)

    op.create_table('platform_c2b_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trans_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bill_ref', sa.String(length=30), nullable=True),
    sa.Column('msisdn', sa.String(length=64), nullable=True),
    sa.Column('payer_name', sa.String(length=120), nullable=True),
    sa.Column('trans_time', sa.String(length=20), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('billing_transaction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billing_transaction_id'], ['billing_transactions.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_c2b_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_c2b_payments_landlord_id'), ['landlord_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_c2b_payments_trans_id'), ['trans_id'], unique=True)

    with op.batch_alter_table('affiliate_withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b2c_originator_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('b2c_conversation_id', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('b2c_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('b2c_result_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('b2c_result_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_unique_constraint('uq_affiliate_withdrawals_b2c_originator_id', ['b2c_originator_id'])

    # NOTE: autogenerate also detected pre-existing schema drift unrelated to
    # this migration (affiliate_referrals/affiliates/copilot_devices index and
    # constraint differences, several created_at NOT NULL tweaks, and
    # sms_pricing_config.updated_at nullability) — left untouched here
    # deliberately. That drift predates MPESA_INTEGRATION_SPEC.md and belongs
    # in its own migration reviewed on its own merits, not bundled silently
    # into an M-Pesa change.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_affiliate_withdrawals_b2c_originator_id', type_='unique')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('b2c_result_desc')
        batch_op.drop_column('b2c_result_code')
        batch_op.drop_column('b2c_status')
        batch_op.drop_column('b2c_conversation_id')
        batch_op.drop_column('b2c_originator_id')

    with op.batch_alter_table('platform_c2b_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_c2b_payments_trans_id'))
        batch_op.drop_index(batch_op.f('ix_platform_c2b_payments_landlord_id'))

    op.drop_table('platform_c2b_payments')
    with op.batch_alter_table('daraja_callback_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daraja_callback_logs_kind'))

    op.drop_table('daraja_callback_logs')
    # ### end Alembic commands ###
