"""payment proof_url + landlord payment_instructions/allocation_priority

Revision ID: 75c4fa4e146b
Revises: 425cd1d75fab
Create Date: 2026-07-03 21:12:20.866352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c4fa4e146b'
down_revision = '425cd1d75fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_instructions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allocation_priority', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('proof_url')

    with op.batch_alter_table('landlords', schema=None) as batch_op:
        batch_op.drop_column('allocation_priority')
        batch_op.drop_column('payment_instructions')

    # ### end Alembic commands ###
