"""initial schema

Revision ID: 9fea422e6169
Revises: 5d205659571c
Create Date: 2026-06-25 22:49:24.365676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fea422e6169'
down_revision = '5d205659571c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_expenses_maintenance_request_id', 'maintenance_requests', ['maintenance_request_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_maintenance_request_id', type_='foreignkey')

    # ### end Alembic commands ###
